---
- stat: path="{{ php_config_prefix }}/fpm/php.ini"
  register: phpfpm

- stat: path="{{ php_config_prefix }}/cli/php.ini"
  register: phpcli

- include: php-fpm.yml
  register: phpfpm.stat.exists

- include: php-cli.yml
  register: phpcli.stat.exists