---

- name: Set timezone in fpm php.ini
  lineinfile: dest="{{ php_config_prefix }}/fpm/php.ini"
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: Enable opcache
  lineinfile: dest="{{ php_config_prefix }}/fpm/php.ini"
              regexp=';?opcache.enable=\d'
              line='opcache.enable=1'

- name: Disable expose_php
  lineinfile: dest="{{ php_config_prefix }}/fpm/php.ini"
              regexp=';?expose_php=\d'
              line='expose_php=0'